version: '3'
services:
  database:
    image: 'postgres:11'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
  schema-migrator:
    build: ./components/schema-migrator
    links:
      - database
    depends_on:
      - database
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_SSL=${DB_SSL}
      - DIRECTION=up
  director:
    build: ./components/director
    links:
      - database
    depends_on:
      - database
      - schema-migrator
    environment:
      - APP_DB_HOST=${DB_HOST}
      - APP_DB_NAME=${DB_NAME}
      - APP_DB_PORT=${DB_PORT}
      - APP_DB_USER=${DB_USER}
      - APP_DB_PASSWORD=${DB_PASSWORD}
      - APP_ADDRESS=0.0.0.0:3000
    ports:
      - '3000:3000'